[package]
name = "omni"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
inquire = "0.7.5"
reqwest = "0.12.4"
serde = "1.0.202"
serde_json = "1.0.117"
termimad = "0.29.2"
tokio = { version = "1.37.0", features = ["full"] }
